# Generated by Django 4.2.14 on 2024-08-06 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment',
        ),
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('10:00', '10:00'), ('11:30', '11:30'), ('13:00', '13:00'), ('14:30', '14:30'), ('16:00', '16:00'), ('17:30', '17:30')], default='10:00', max_length=10),
        ),
    ]
