# Generated by Django 4.2.14 on 2024-08-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stylist_booking_stylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='stylist_name',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Stylist',
        ),
    ]
