# Generated by Django 4.2.14 on 2024-08-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='specialties',
            new_name='speciality',
        ),
    ]
